# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # don't do this with this password in production
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USER: acme
    ports:
      - 8001:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080